### ISSUE TITLE
add redux

### ISSUE THREAD

**Issue by justrdk** [AcklenAvenue/react-boilerplate#11]

**Comment by ferenckv** [comment]
https://medium.com/@notrab/getting-started-with-create-react-app-redux-react-router-redux-thunk-d6a19259f71f

**Comment by ferenckv** [comment]
Will we use observables?

**Comment by justrdk** [comment]
I believe the redux official docs are better for integrating redux. Redux-thunk should work. If people want to use sagas or observables they can add them to their project.

Redux state persistent after refreshing the screen should be set as well.

https://github.com/rt2zz/redux-persist

**Comment by ferenckv** [comment]
https://github.com/bsommardahl/react-boilerplate/pull/24

@justrdk, @bsommardahl: Things to consider before merging this PR:

- Are we going to use Reselect? it's not added yet.
- How are we going to manage flow types? Right now, it assuming we're having a file types.js inside every component.
- Since I added two components to demonstrate the use of stores, I applied this structure to the code:
```
  - src
    - modules
      - <Module Name>
        - tests
          - index.test.js
          - reducer.test.js
          - <Stateless Component 1>.test.js
        - index.js
        - reducer.js
        - types.js
        - <Stateless Component 1>.js
    - services
```

Is this structure OK? Should I change something?

**Comment by dantedubonc** [comment]
Reselect is important because it simplify the work with large states

**Comment by dantedubonc** [comment]
@ferenckv are we talking about containers and components with this structure?
